// <auto-generated />
using System;
using GlaucomaWay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlaucomaWay.Migrations
{
    [DbContext(typeof(GlaucomaDbContext))]
    [Migration("20211026181707_CreatePatients")]
    partial class CreatePatients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GlaucomaWay.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BithDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("GlaucomaWay.Models.Vf14ResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<short>("Q10Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q11Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q12Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q13Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q14Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q1Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q2Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q3Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q4Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q5Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q6Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q7Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q8Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Q9Score")
                        .HasColumnType("smallint");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Vf14Results");
                });

            modelBuilder.Entity("GlaucomaWay.Models.Vf14ResultModel", b =>
                {
                    b.HasOne("GlaucomaWay.Models.PatientModel", "Patient")
                        .WithMany("Results")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GlaucomaWay.Models.PatientModel", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
